"""
End-to-end replay of REAL video data through the shipped TypeScript pipeline.

Every other test either uses synthetic landmarks or compares against fixtures
generated by Python. This one takes the actual per-frame features extracted
from the 144 labelled videos and pushes them through the compiled TypeScript
packages -- the same code the browser runs -- then compares against the
Python reference that produced the training data.

That is the only place where "the browser pipeline works on real data" is
actually checked rather than assumed.

Requires:
  * ml/data/processed/*.npz  (real extractions; regenerate with `npm run ml:pipeline -- --full`)
  * node on PATH
  * packages/*/dist built    (npm run build:packages)

Skips (loudly) if the real extractions are absent -- this cannot be faked.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "ml" / "data" / "processed"
FIXTURE = ROOT / "tests" / "fixtures" / "replay_real_video.json"
RUNNER = ROOT / "tests" / "replay_runner.mjs"
MAKER = ROOT / "tests" / "make_replay_fixture.py"

# float32 is the storage dtype of the extracted frames, so agreement can never
# be better than roughly this. Anything above it is a real divergence.
AGGREGATION_TOLERANCE = 1e-3


def _python() -> str:
    return sys.executable


def _load_replay() -> dict:
    if not list(PROCESSED.glob("*.npz")):
        pytest.skip(
            "no real extractions in ml/data/processed -- "
            "run `npm run ml:pipeline -- --full` first; this cannot be faked"
        )
    if shutil.which("node") is None:
        pytest.skip("node not on PATH")

    # Regenerate the fixture from whatever is currently on disk, so this test
    # can never pass against a stale snapshot of the data.
    subprocess.run([_python(), str(MAKER)], cwd=str(ROOT), check=True,
                   capture_output=True)

    res = subprocess.run(
        ["node", str(RUNNER)], cwd=str(ROOT), capture_output=True, text=True
    )
    if res.returncode != 0:
        pytest.fail(f"replay_runner.mjs failed ({res.returncode}):\n{res.stderr}")
    return json.loads(res.stdout)


@pytest.fixture(scope="module")
def replay() -> dict:
    return _load_replay()


def test_replay_covers_real_reps(replay: dict) -> None:
    """The replay must actually exercise a meaningful number of real reps."""
    s = replay["summary"]
    assert s["nCases"] > 0, "replay found no clips"
    assert s["aggregationRepsCompared"] >= 20, (
        f"only {s['aggregationRepsCompared']} real reps compared -- too few to trust"
    )


def test_typescript_aggregation_matches_python_on_real_data(replay: dict) -> None:
    """The browser's rep-window aggregation must reproduce Python's vector.

    Before the timestamp corruption was fixed this disagreed by up to 26.7
    (seconds, on rep_duration_s). It now agrees to float32 precision.
    """
    worst = replay["summary"]["aggregationMaxAbsDiff"]
    assert worst < AGGREGATION_TOLERANCE, (
        f"aggregation diverged: max |ts - python| = {worst:.3e} "
        f"(worst features: {replay['summary']['worstAggregationFeatures'][:3]})"
    )


def test_no_case_counts_zero_reps_where_python_finds_them(replay: dict) -> None:
    """A clip with real push-ups must never come back as zero reps.

    This is the catastrophic failure mode: thresholds calibrated on a
    non-stationary prefix become unreachable and the FSM never transitions,
    so the counter silently reports nothing while looking healthy.
    """
    zeros = [
        c["name"]
        for c in replay["cases"]
        if c["repCount"]["python"] > 0 and c["repCount"]["tsAdaptive"] == 0
    ]
    assert not zeros, f"counted zero reps on clips with real reps: {zeros}"


def test_adaptive_rep_count_tracks_python(replay: dict) -> None:
    """Adaptive re-calibration must recover most of the real rep counts.

    Individual clips can differ (the two segmenters are different algorithms),
    but the totals must be close, and the adaptive path must beat the locked
    one -- otherwise the added complexity is not paying for itself.
    """
    rc = replay["summary"]["repCount"]
    total_python = rc["totalPython"]

    assert total_python > 0
    err_adaptive = rc["totalAbsErrAdaptive"]
    err_locked = rc["totalAbsErrLive"]

    # Adaptive must not be worse than locked-once.
    assert err_adaptive <= err_locked, (
        f"adaptive recalibration made counting worse: "
        f"{err_adaptive} vs locked {err_locked}"
    )
    # And must be within 25% of the reference total.
    assert err_adaptive <= 0.25 * total_python, (
        f"rep count error too large: {err_adaptive} off a true total of {total_python}"
    )


def test_replay_reports_no_case_errors(replay: dict) -> None:
    if replay.get("errors"):
        pytest.fail(f"replay runner reported errors: {replay['errors'][:5]}")


def test_replayed_rep_durations_are_physically_plausible(replay: dict) -> None:
    """Guard the corruption at the data layer too.

    A push-up takes roughly 0.5-6 s. The corrupted extractions reported up to
    21.9 s. If repaired data ever regresses, this fails even if both
    implementations agree with each other.
    """
    bad = []
    for case in replay["cases"]:
        for rep in case.get("aggregation", {}).get("repDurations", []) or []:
            if rep["python"] is None:
                continue
            if not (0.2 <= rep["python"] <= 8.0):
                bad.append((case["name"], rep["index"], rep["python"]))
    assert not bad, f"implausible rep durations in extracted data: {bad[:5]}"
